"""fg

Revision ID: 2a315a6ecb18
Revises: d727eae3f9b9
Create Date: 2025-04-18 12:41:29.343476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a315a6ecb18'
down_revision = 'd727eae3f9b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['invoice_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###
