"""chang

Revision ID: 62b0aa0d4514
Revises: e9eb69714a75
Create Date: 2025-04-18 01:54:27.310212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '62b0aa0d4514'
down_revision = 'e9eb69714a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('supplier',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index('invoice_id')
        batch_op.drop_column('invoice_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_id', mysql.VARCHAR(length=20), nullable=True))
        batch_op.create_index('invoice_id', ['invoice_id'], unique=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('total',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('supplier',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
