"""cha

Revision ID: aa01b3ccdeaa
Revises: 62b0aa0d4514
Create Date: 2025-04-18 03:40:24.464813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa01b3ccdeaa'
down_revision = '62b0aa0d4514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint('purchase_ibfk_1', type_='foreignkey')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('purchase_ibfk_1', 'product', ['product_id'], ['id'])

    # ### end Alembic commands ###
