"""c

Revision ID: afb4601e8f35
Revises: 3a4f6b81ba01
Create Date: 2025-04-18 12:18:12.657570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'afb4601e8f35'
down_revision = '3a4f6b81ba01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller', sa.String(length=100), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('product')
        batch_op.drop_column('customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('product', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.drop_column('seller')

    # ### end Alembic commands ###
