"""Increased password_hash length

Revision ID: e9eb69714a75
Revises: 9ca28563ff3c
Create Date: 2025-04-17 22:20:59.200918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9eb69714a75'
down_revision = '9ca28563ff3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('supplier', sa.String(length=100), nullable=True))
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_constraint('product_ibfk_1', type_='foreignkey')
        batch_op.drop_column('category_id')
        batch_op.drop_column('description')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('product_ibfk_1', 'category', ['category_id'], ['id'])
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('stock',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('supplier')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
